apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsp-api
  template:
    metadata:
      labels:
        app: tsp-api
    spec:
      containers:
        - name: tsp-api
          image: docker.io/titoeb/genetic-algorithm-tsp-api:40e24888052f7ec5269b3b9fe3e3ab867d322b74
          env:
            - name: ROCKET_WORKERS
              value: "2"
          resources:
            requests:
              memory: "40Mi"
              cpu: "1"
            limits:
              memory: "60Mi"
              cpu: "1"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /alive
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /alive
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: tsp-api-service
spec:
  selector:
    app: tsp-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tsp-api-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tsp-api-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageUtilization: 40
